name: "Semantic Monorepo"
description: "Automated releases for multipackage monorepo"
author: "Maciek Pekala"
branding:
  icon: "package"
  color: "purple"

inputs:
  myInput:
    description: "Input to use"
    default: "world"
runs:
  using: "node12"
  main: "lib/main.js"
